apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.global.deploymentPrefix }}ph-product-service
  name: {{ .Values.global.deploymentPrefix }}ph-product-service
spec:
  ports:
  - name: 80-8085
    port: 80
    protocol: TCP
    targetPort: 8085
  selector:
    app: {{ .Values.global.deploymentPrefix }}ph-product-service
  type: ClusterIP