apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-set-planthub 
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: ph-product-service
      - name: hmi-service 
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/vanonnahenrik/argocd-with-helm'
        path: charts/{{name}}-chart
        targetRevision: main 
        helm:
          valueFiles:
            - '../../config/helm-{{name}}-values.yaml'
        envFrom:
          - configMapRef:
              name: {{name}}-env-config
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
