apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config 
  labels:
    app: test-config
data:
  application.properties: |-
  {{- range $key, $val := .Values.envConfigMap}}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
