apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app 
  namespace: argocd 
spec:
  project: default
  source:
    repoURL: https://github.com/vanonnahenrik/argocd-with-helm 
    targetRevision: main
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
     - CreateNamespace=true
