apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-tester
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: alpine
          image: alpine:3
          command:
            - /bin/sh
            - -c
            - while true; do echo "$(date)  $(cat /etc/config/myconfig.ini)";
              sleep 10; done;
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: application-properties-configmap
