apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ph-product-service
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: 'https://github.com/vanonnahenrik/argocd-with-helm'
    path: charts/ph-product-service-chart
    targetRevision: main
    helm:
      releaseName: ph-product-service
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
