apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ph-product-service
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  sources:
  - repoURL: 'https://github.com/vanonnahenrik/argocd-with-helm'
    path: charts/ph-product-service-chart
    targetRevision: main
    helm:
      valueFiles:
      - '${values}/config/helm-ph-product-service-values.yaml'
  - repoURL: 'https://github.com/vanonnahenrik/argocd-with-helm'
    targetRevision: argotag 
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
